pull_request_rules:
  - name: automatic merge when CI passes and 1 review
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=continuous-integration/appveyor/pr
      - status-success=WIP
      - base=master
    actions:
      merge:
        strict: smart
        method: squash
  - name: automatic merge when CI passes and user is JourneyOver
    conditions:
      - author=JourneyOver
      - status-success=continuous-integration/appveyor/pr
      - status-success=WIP
      - base=master
    actions:
      merge:
        strict: smart
        method: squash
  - name: automatic merge when user is imgbot[bot]
    conditions:
      - author=imgbot[bot]
      - status-success=continuous-integration/appveyor/pr
      - base=master
    actions:
      merge:
        strict: smart
        method: squash
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
